[package]
name = "smarthome-sdk-rs"
description = "A Rust client-library which makes communication with the Smarthome server easy"
version = "0.1.0"
license = "GPL-2.0-only"
repository = "https://github.com/smarthome-go/sdk-rs"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
reqwest = { version = "0.11.11", features = [
  "json",
  "rustls-tls",
], default-features = false }
semver = "1.0.13"
serde = { version = "1.0.144", features = ["derive"] }
tokio = { version = "1.20.1", features = ["full"] }
url = "2.2.2"
